# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bonsai"
  s.version = "1.4.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Schwarz"]
  s.date = "2012-06-24"
  s.description = "A static site generator that uses the best toolset available"
  s.email = "ben.schwarz@gmail.com"
  s.executables = ["bonsai"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".bundle/config",
    ".document",
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "CHANGES",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "benchmark/associations.rb",
    "bin/bonsai",
    "bonsai.gemspec",
    "ci.sh",
    "lib/bonsai.rb",
    "lib/bonsai/console.rb",
    "lib/bonsai/exporter.rb",
    "lib/bonsai/generate.rb",
    "lib/bonsai/navigation.rb",
    "lib/bonsai/page.rb",
    "lib/bonsai/sitemap.rb",
    "lib/bonsai/template.rb",
    "lib/bonsai/templates/.gitignore",
    "lib/bonsai/templates/content/1.varieties/1.fig/default.yml",
    "lib/bonsai/templates/content/1.varieties/2.maple/default.yml",
    "lib/bonsai/templates/content/1.varieties/3.magic/images/magic.jpg",
    "lib/bonsai/templates/content/1.varieties/3.magic/magic.yml",
    "lib/bonsai/templates/content/1.varieties/products.yml",
    "lib/bonsai/templates/content/2.cultivation/default.yml",
    "lib/bonsai/templates/content/3.history/default.yml",
    "lib/bonsai/templates/content/index/default.yml",
    "lib/bonsai/templates/public/.htaccess",
    "lib/bonsai/templates/public/css/base.scss",
    "lib/bonsai/templates/public/robots.txt",
    "lib/bonsai/templates/site.yml",
    "lib/bonsai/templates/templates/default.liquid",
    "lib/bonsai/templates/templates/magic.liquid",
    "lib/bonsai/templates/templates/products.liquid",
    "lib/bonsai/templates/templates/shared/_analytics.liquid",
    "lib/bonsai/templates/templates/shared/_breadcrumbs.liquid",
    "lib/bonsai/templates/templates/shared/_footer.liquid",
    "lib/bonsai/templates/templates/shared/_head.liquid",
    "lib/bonsai/templates/templates/shared/_header.liquid",
    "lib/bonsai/templates/templates/shared/_nav.liquid",
    "lib/bonsai/webserver.rb",
    "lib/bonsai/webserver/error.erb",
    "lib/core_ext/string.rb",
    "spec/bonsai/console_spec.rb",
    "spec/bonsai/exporter_spec.rb",
    "spec/bonsai/generate_spec.rb",
    "spec/bonsai/navigation_spec.rb",
    "spec/bonsai/page_spec.rb",
    "spec/bonsai/sitemap_spec.rb",
    "spec/bonsai/template_spec.rb",
    "spec/bonsai_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/support/broken/content/broken_page/demo-template.yml",
    "spec/support/broken/public/empty.txt",
    "spec/support/broken/site.yml",
    "spec/support/broken/templates/content/index/default.yml",
    "spec/support/broken/templates/public/.htaccess",
    "spec/support/broken/templates/public/docs/css/base.less",
    "spec/support/broken/templates/public/robots.txt",
    "spec/support/broken/templates/templates/default.mustache",
    "spec/support/content/1.about-us/1.contact/1.child/a_file_asset.txt",
    "spec/support/content/1.about-us/1.contact/1.child/demo-template.yml",
    "spec/support/content/1.about-us/1.contact/demo-template.yml",
    "spec/support/content/1.about-us/1.contact/magic/image001.jpg",
    "spec/support/content/1.about-us/1.contact/magic/image002.jpg",
    "spec/support/content/1.about-us/demo-template.yml",
    "spec/support/content/1.about-us/history/001.jpg",
    "spec/support/content/1.about-us/history/1_a_file_asset.txt",
    "spec/support/content/1.about-us/history/child/a_file_asset.txt",
    "spec/support/content/1.about-us/history/child/demo-template.yml",
    "spec/support/content/1.about-us/history/demo-template.yml",
    "spec/support/content/1.about-us/history/images/image001.jpg",
    "spec/support/content/1.about-us/history/magic/image001.jpg",
    "spec/support/content/1.about-us/history/magic/image002.jpg",
    "spec/support/content/10.many-pages/demo-template.yml",
    "spec/support/content/2.products/1.product-a/demo-template.yml",
    "spec/support/content/2.products/2.product-b/demo-template.yml",
    "spec/support/content/2.products/demo-template.yml",
    "spec/support/content/index/demo-template.yml",
    "spec/support/content/legals/terms-and-conditions/demo-template.yml",
    "spec/support/content/render/image-spec/images.yml",
    "spec/support/content/render/image-spec/images/image001.jpg",
    "spec/support/extensions.rb",
    "spec/support/public/.htaccess",
    "spec/support/public/js/script.js",
    "spec/support/public/stylesheets/brokensass.sass",
    "spec/support/public/stylesheets/sassy.css",
    "spec/support/public/stylesheets/sassy.scss",
    "spec/support/site.yml",
    "spec/support/templates/children.liquid",
    "spec/support/templates/demo-template.liquid",
    "spec/support/templates/images.liquid",
    "spec/support/templates/partials/_inserted.liquid",
    "spec/support/templates/partials/_magic.liquid",
    "vendor/yui-compressor/yuicompressor-2.4.2.jar"
  ]
  s.homepage = "http://github.com/benschwarz/bonsai"
  s.post_install_message = "\n\n      \u{76c6}\u{683d}\n      bonsai, tiny and beautiful\n\n\n\n      type `bonsai --help` to get started\n    "
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "A static site generator that uses the best toolset available"
  s.test_files = [
    "spec/bonsai/console_spec.rb",
    "spec/bonsai/exporter_spec.rb",
    "spec/bonsai/generate_spec.rb",
    "spec/bonsai/navigation_spec.rb",
    "spec/bonsai/page_spec.rb",
    "spec/bonsai/sitemap_spec.rb",
    "spec/bonsai/template_spec.rb",
    "spec/bonsai_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/extensions.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bonsai>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0"])
      s.add_runtime_dependency(%q<tilt>, [">= 1.3"])
      s.add_runtime_dependency(%q<liquid>, [">= 2.2.2"])
      s.add_runtime_dependency(%q<builder>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<watch>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<maruku>, [">= 0.6.0"])
      s.add_runtime_dependency(%q<launchy>, [">= 0.3.7"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.3"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<sass>, [">= 0"])
    else
      s.add_dependency(%q<bonsai>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 1.0"])
      s.add_dependency(%q<tilt>, [">= 1.3"])
      s.add_dependency(%q<liquid>, [">= 2.2.2"])
      s.add_dependency(%q<builder>, [">= 3.0.0"])
      s.add_dependency(%q<watch>, [">= 0.1.0"])
      s.add_dependency(%q<maruku>, [">= 0.6.0"])
      s.add_dependency(%q<launchy>, [">= 0.3.7"])
      s.add_dependency(%q<activesupport>, [">= 3.0.3"])
      s.add_dependency(%q<i18n>, [">= 0.5.0"])
      s.add_dependency(%q<sass>, [">= 0"])
    end
  else
    s.add_dependency(%q<bonsai>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.7.5"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.7.5"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.7.5"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.7.5"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.7.5"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 1.0"])
    s.add_dependency(%q<tilt>, [">= 1.3"])
    s.add_dependency(%q<liquid>, [">= 2.2.2"])
    s.add_dependency(%q<builder>, [">= 3.0.0"])
    s.add_dependency(%q<watch>, [">= 0.1.0"])
    s.add_dependency(%q<maruku>, [">= 0.6.0"])
    s.add_dependency(%q<launchy>, [">= 0.3.7"])
    s.add_dependency(%q<activesupport>, [">= 3.0.3"])
    s.add_dependency(%q<i18n>, [">= 0.5.0"])
    s.add_dependency(%q<sass>, [">= 0"])
  end
end

